import React from 'react'
import ReactDOM from 'react-dom/client'
import Gantt from './index'
import 'antd/dist/antd.css';
import moment from "moment";

const res: { [key: string]: any } = {
  "brandonxiang1": [
    {
      jira_id: "4191121",
      jira_key: "ABCDE-54612",
      summary: "abcde 字段 Data Masking 数据屏蔽开发",
      issue_type: "Sub-task",
      status: "Doing",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667318400,
      dev_due_date: 1667404800,
      qa_due_date: 0,
      story_points: 2,
      priority: "Medium",
      parent_id: "4139642",
      parent_key: "ABCDE-54487",
      parent_summary: "XYC Project -abcde/XYZ",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang1",
    },
    {
      jira_id: "4191128",
      jira_key: "ABCDE-54613",
      summary: "XYZ 字段 Data Masking 数据屏蔽开发",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667491200,
      dev_due_date: 1667491200,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4139642",
      parent_key: "ABCDE-54487",
      parent_summary: "XYC Project -abcde/XYZ",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang1",
    },
    {
      jira_id: "4191143",
      jira_key: "ABCDE-54614",
      summary: "abcde/XYZ Data Masking 数据屏蔽自测",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667836800,
      dev_due_date: 1667836800,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4139642",
      parent_key: "ABCDE-54487",
      parent_summary: "XYC Project -abcde/XYZ",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang1",
    },
    {
      jira_id: "4194834",
      jira_key: "ABCDE-54620",
      summary: "abcde/XYZ 字段 Data Masking 数据屏蔽UI",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667750400,
      dev_due_date: 1667750400,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4139642",
      parent_key: "ABCDE-54487",
      parent_summary: "XYC Project -abcde/XYZ",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang1",
    },
  ],
  "brandonxiang2": [
    {
      jira_id: "4190844",
      jira_key: "ABCDE-54604",
      summary: "【页面任务】Provide Status Information in the ABSsion Campaign",
      issue_type: "Sub-task",
      status: "Doing",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667404800,
      dev_due_date: 1667491200,
      qa_due_date: 0,
      story_points: 0.5,
      priority: "Medium",
      parent_id: "4190824",
      parent_key: "ABCDE-54603",
      parent_summary:
        "[Team][abcde][abcde in Partner]Provide Status Information in the ABSsion Campaign",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang2",
    },
    {
      jira_id: "4190860",
      jira_key: "ABCDE-54605",
      summary:
        "【自测与联调】Provide Status Information in the ABSsion Campaign",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667923200,
      dev_due_date: 1667923200,
      qa_due_date: 0,
      story_points: 0.5,
      priority: "Medium",
      parent_id: "4190824",
      parent_key: "ABCDE-54603",
      parent_summary:
        "[Team][abcde][abcde in Partner]Provide Status Information in the ABSsion Campaign",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang2",
    },
    {
      jira_id: "4194806",
      jira_key: "ABCDE-54619",
      summary: "【挂单】【CICD】abcdefBot Webhook适配“有点帅”分支模型",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667491200,
      dev_due_date: 1667491200,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4190824",
      parent_key: "ABCDE-54603",
      parent_summary:
        "[Team][abcde][abcde in Partner]Provide Status Information in the ABSsion Campaign",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang2",
    },
    {
      jira_id: "4194929",
      jira_key: "qwe18922",
      summary: "[Team]熟悉 abcdef 业务逻辑与相关代码及仓库环境配置",
      issue_type: "Sub-task",
      status: "Doing",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667318400,
      dev_due_date: 1667404800,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4155445",
      parent_key: "qwe18642",
      parent_summary:
        "Mother/Child/Entity/Bank Changes based on mmmsss",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang2",
    },
  ],
  "brandonxiang3": [
    {
      jira_id: "4191029",
      jira_key: "ABCDE-54609",
      summary: "Bill类商品价格接口逻辑联调",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667318400,
      dev_due_date: 1667404800,
      qa_due_date: 0,
      story_points: 2,
      priority: "Medium",
      parent_id: "4191023",
      parent_key: "ABCDE-54608",
      parent_summary: "[Team]Product Fee calculate logic enhancement",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang3",
    },
    {
      jira_id: "4191037",
      jira_key: "ABCDE-54610",
      summary: "abcdef接口金额计算逻辑联调",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667404800,
      dev_due_date: 1667491200,
      qa_due_date: 0,
      story_points: 1.5,
      priority: "Medium",
      parent_id: "4191023",
      parent_key: "ABCDE-54608",
      parent_summary: "[Team]Product Fee calculate logic enhancement",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang3",
    },
    {
      jira_id: "4191059",
      jira_key: "ABCDE-54611",
      summary: "Product Fee价格展示全商品review和自测",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667750400,
      dev_due_date: 1667750400,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4191023",
      parent_key: "ABCDE-54608",
      parent_summary: "[Team]Product Fee calculate logic enhancement",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang3",
    },
    {
      jira_id: "4191097",
      jira_key: "qwe18868",
      summary: "[Team]2022.10.31-11.04 值班",
      issue_type: "Sub-task",
      status: "Doing",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667145600,
      dev_due_date: 1667491200,
      qa_due_date: 0,
      story_points: 1.5,
      priority: "Medium",
      parent_id: "4188250",
      parent_key: "qwe18851",
      parent_summary: "FE值班",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang3",
    },
    {
      jira_id: "4191146",
      jira_key: "qwe18870",
      summary: "[Team]abcdef 1010版本发布",
      issue_type: "Sub-task",
      status: "Done",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667232000,
      dev_due_date: 1667404800,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4191123",
      parent_key: "qwe18869",
      parent_summary: "FE版本发布任务",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang3",
    },
  ],
  "brandonxiang4": [
    {
      jira_id: "4190866",
      jira_key: "abMMMMM-18534",
      summary: "[Team][MMMM][ALL]XYC -- 各个模块加密字段处理",
      issue_type: "Sub-task",
      status: "Doing",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667232000,
      dev_due_date: 1667491200,
      qa_due_date: 0,
      story_points: 3,
      priority: "Medium",
      parent_id: "4158212",
      parent_key: "abMMMMM-18457",
      parent_summary:
        "[Team][MMMM][ALL]XYC: enhance all portal senstive operation to avoid info leak",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang4",
    },
    {
      jira_id: "4201179",
      jira_key: "abMMMMM-18568",
      summary: "[Team][MMMM] SupportabcdefDownload",
      issue_type: "Sub-task",
      status: "Doing",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667491200,
      dev_due_date: 1667491200,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4201173",
      parent_key: "abMMMMM-18567",
      parent_summary:
        "[Team][MMMM] Support abcdef Download -- 开发联调",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang4",
    },
  ],
  "brandonxiang5": [
    {
      jira_id: "4071235",
      jira_key: "qwe18130",
      summary: "[Team]【review summary detail】字段详情改造 ",
      issue_type: "Sub-task",
      status: "Done",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667318400,
      dev_due_date: 1667404800,
      qa_due_date: 0,
      story_points: 2,
      priority: "Medium",
      parent_id: "4071147",
      parent_key: "qwe18125",
      parent_summary: "Approve Center",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang5",
    },
    {
      jira_id: "4071252",
      jira_key: "qwe18131",
      summary: "[Team]【review center】homepage 改造",
      issue_type: "Sub-task",
      status: "Doing",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667491200,
      dev_due_date: 1667491200,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4071147",
      parent_key: "qwe18125",
      parent_summary: "Approve Center",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang5",
    },
    {
      jira_id: "4071272",
      jira_key: "qwe18132",
      summary:
        "[Team]【review center detail】time \u0026\u0026 systemtag \u0026\u0026 new Tag 改造",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667750400,
      dev_due_date: 1667923200,
      qa_due_date: 0,
      story_points: 3,
      priority: "Medium",
      parent_id: "4071147",
      parent_key: "qwe18125",
      parent_summary: "Approve Center",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang5",
    },
  ],
  "brandonxiang6": [
    {
      jira_id: "4063690",
      jira_key: "ABCDE-54313",
      summary: "写开源Folderabcdef 仓库的README文档",
      issue_type: "Sub-task",
      status: "Doing",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667404800,
      dev_due_date: 1667491200,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "1995748",
      parent_key: "ABCDE-42185",
      parent_summary: "[Team]差分服务",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang6",
    },
    {
      jira_id: "4194550",
      jira_key: "ABCDE-54618",
      summary:
        "填写差分优化公司级分享的标题、摘要、分段详情、作者简介等中英文信息",
      issue_type: "Sub-task",
      status: "Done",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667404800,
      dev_due_date: 1667491200,
      qa_due_date: 0,
      story_points: 0.5,
      priority: "Medium",
      parent_id: "1995748",
      parent_key: "ABCDE-42185",
      parent_summary: "[Team]差分服务",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang6",
    },
  ],
  "brandonxiang7": [
    {
      jira_id: "4160350",
      jira_key: "abMMMMM-18468",
      summary:
        "[Team]Bulk toggle retrieve request device-列表页面（带search bar）",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667318400,
      dev_due_date: 1667491200,
      qa_due_date: 0,
      story_points: 2,
      priority: "Medium",
      parent_id: "3670625",
      parent_key: "abMMMMM-17690",
      parent_summary: "[Team]inventory重构",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang7",
    },
    {
      jira_id: "4160356",
      jira_key: "abMMMMM-18469",
      summary: "[Team]Bulk toggle retrieve request device-新增模态框",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667491200,
      dev_due_date: 1667750400,
      qa_due_date: 0,
      story_points: 1.5,
      priority: "Medium",
      parent_id: "3670625",
      parent_key: "abMMMMM-17690",
      parent_summary: "[Team]inventory重构",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang7",
    },
    {
      jira_id: "4160368",
      jira_key: "abMMMMM-18470",
      summary: "[Team]Transfer Device：新增字段 + 替换模版",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667836800,
      dev_due_date: 1667923200,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "3670625",
      parent_key: "abMMMMM-17690",
      parent_summary: "[Team]inventory重构",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang7",
    },
  ],
  "brandonxiang8": [
    {
      jira_id: "4148713",
      jira_key: "qwe18513",
      summary: "[Team]详情页加密解密数据联调",
      issue_type: "Sub-task",
      status: "To Do",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667836800,
      dev_due_date: 1667836800,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4141035",
      parent_key: "qwe18469",
      parent_summary: "[TW][BR]ABS Admin 明文加密交互",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang8",
    },
    {
      jira_id: "4181812",
      jira_key: "qwe18805",
      summary: "[Team]Support MMABCDEFG Market Web Services 改造",
      issue_type: "Sub-task",
      status: "Done",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667404800,
      dev_due_date: 1667404800,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4181807",
      parent_key: "qwe18804",
      parent_summary:
        "[Team]Support MMABCDEFG Transaction History in VN Market Web",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang8",
    },
    {
      jira_id: "4182006",
      jira_key: "qwe18812",
      summary: "[Team]Ops Operation Support",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667923200,
      dev_due_date: 1668009600,
      qa_due_date: 0,
      story_points: 2,
      priority: "Medium",
      parent_id: "4181993",
      parent_key: "qwe18811",
      parent_summary: "[Team]Ops Operation Support",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang8",
    },
    {
      jira_id: "4183717",
      jira_key: "qwe18831",
      summary:
        '[Team][Team]Support the "Use National QR Standard" toggle for TH/VN',
      issue_type: "Sub-task",
      status: "Doing",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667750400,
      dev_due_date: 1667750400,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4181968",
      parent_key: "qwe18809",
      parent_summary:
        '[Team]Support the "Use National QR Standard" toggle for TH/VN',
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang8",
    },
    {
      jira_id: "4188768",
      jira_key: "qwe18856",
      summary: "[Team]支持 MMABCDEFG 子应用弹框",
      issue_type: "Sub-task",
      status: "Doing",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667491200,
      dev_due_date: 1667491200,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4181807",
      parent_key: "qwe18804",
      parent_summary:
        "[Team]Support MMABCDEFG Transaction History in VN Market Web",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang8",
    },
  ],
  "brandonxiang9": [
    {
      jira_id: "4154576",
      jira_key: "abMMMMM-18435",
      summary: "[Team][Page: Device Detail] 15个字段变更且涉及类型判断",
      issue_type: "Sub-task",
      status: "Doing",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667404800,
      dev_due_date: 1667750400,
      qa_due_date: 0,
      story_points: 2,
      priority: "Medium",
      parent_id: "3670625",
      parent_key: "abMMMMM-17690",
      parent_summary: "[Team]inventory重构",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang9",
    },
    {
      jira_id: "4154596",
      jira_key: "abMMMMM-18437",
      summary: "[Team][Page: Device Detail] 详情编辑功能",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667836800,
      dev_due_date: 1667923200,
      qa_due_date: 0,
      story_points: 1.5,
      priority: "Medium",
      parent_id: "3670625",
      parent_key: "abMMMMM-17690",
      parent_summary: "[Team]inventory重构",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang9",
    },
  ],
  "brandonxiang10": [
    {
      jira_id: "4140357",
      jira_key: "qwe18465",
      summary: "[Team]腾讯云 cos文件双写到uss",
      issue_type: "Sub-task",
      status: "Done",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667404800,
      dev_due_date: 1667491200,
      qa_due_date: 0,
      story_points: 2,
      priority: "Medium",
      parent_id: "3245149",
      parent_key: "qwe14831",
      parent_summary: "web 业务组件库",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang10",
    },
    {
      jira_id: "4190859",
      jira_key: "qwe18866",
      summary:
        "[Team]Support API access config per API access toggle on application entities UI",
      issue_type: "Sub-task",
      status: "Doing",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667750400,
      dev_due_date: 1667836800,
      qa_due_date: 0,
      story_points: 1.5,
      priority: "Medium",
      parent_id: "4190851",
      parent_key: "qwe18865",
      parent_summary:
        "Support API access config per API access toggle on application entities",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang10",
    },
    {
      jira_id: "4191558",
      jira_key: "qwe18873",
      summary: "[Team][qwe18639][BE]PRD预评审 评审",
      issue_type: "Sub-task",
      status: "Done",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667404800,
      dev_due_date: 1667404800,
      qa_due_date: 0,
      story_points: 0.5,
      priority: "Medium",
      parent_id: "4155390",
      parent_key: "qwe18635",
      parent_summary: "mmmsss 服务端方案设计",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang10",
    },
    {
      jira_id: "4201363",
      jira_key: "qwe19009",
      summary: "[Team]TH][MIS Admin]Entity UI",
      issue_type: "Sub-task",
      status: "TO DO",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667836800,
      dev_due_date: 1668009600,
      qa_due_date: 0,
      story_points: 2,
      priority: "Medium",
      parent_id: "4155445",
      parent_key: "qwe18642",
      parent_summary:
        "Mother/Child/Entity/Bank Changes based on mmmsss",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang10",
    },
  ],
  "brandonxiang11": [
    {
      jira_id: "4185508",
      jira_key: "qwe18843",
      summary: "[Team]MY / TH 审批模式 可编辑模块设计 ",
      issue_type: "Sub-task",
      status: "Doing",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667404800,
      dev_due_date: 1667404800,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4015838",
      parent_key: "qwe17968",
      parent_summary: " Approve Center 2.0",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang11",
    },
    {
      jira_id: "4185512",
      jira_key: "qwe18844",
      summary: "[Team]MY / TH 审批模式 可编辑模块 字段 \u0026 表单组件",
      issue_type: "Sub-task",
      status: "Doing",
      start_date: 0,
      due_date: 0,
      dev_start_date: 1667491200,
      dev_due_date: 1667491200,
      qa_due_date: 0,
      story_points: 1,
      priority: "Medium",
      parent_id: "4015838",
      parent_key: "qwe17968",
      parent_summary: " Approve Center 2.0",
      requirement_type: "",
      update_date: 0,
      assignee: "brandonxiang11",
    },
  ],
};

const initStart = moment().subtract(10, "days");
const initEnd = moment().add(6, "days");

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <Gantt data={res} startDate={initStart} endDate={initEnd}/>
  </React.StrictMode>
)